apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DATABASE_URL: "postgres://user:SuperSecretPassword123@rc1a-01c9bpon4l4scrtn.mdb.yandexcloud.net:6432/cis_engine?sslmode=verify-full"
