# k8s/03-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cis-api-service
spec:
  type: LoadBalancer
  selector:
    app: cis-engine
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
